name: backend
publish_to: none
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>


environment:
  sdk: 2.7.2

dependencies:
  aqueduct: ^3.0.0+1
  googleapis: 0.56.1
  googleapis_auth: 0.2.12+1
  models:
    path: /Users/rogge/developer/courses/tddd27/shared/models


dependency_overrides:
  postgres: 2.1.1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0