name: models
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^2.10.4

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
